name: Run Python Script with ENV
on: workflow_dispatch

jobs:
  run-it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Python script with environment variable
        env:
          IMIE: "Marek"   # tutaj możesz wpisać swoje imię
        run: python3 script.py
